apiVersion: v1
kind: Service
metadata:
  name: tech-app-service
spec:
  selector:
    app: nodejs-hello-world
  ports:
    - name: http
      port: 81
      targetPort: 8080
  loadBalancerIP: 35.200.222.213
  type: LoadBalancer